import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import AuthProvider from "@/context/AuthProvider";
import { CartContextProvider } from "@/context/CartContext";
import { Toaster } from "@/components/ui/sonner"
import { WishlistContextProvider } from "@/context/WishlistContext";
import Footer from "./_Components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CartContextProvider>
            <WishlistContextProvider>
              <Navbar />
              <main className="flex-1">
                {children}
              </main>
              <Footer />
              <Toaster position="bottom-right" richColors />
            </WishlistContextProvider>
          </CartContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
